### ISSUE TITLE
Build script should check for existence of `Kalman` etc

### ISSUE THREAD

**Issue by mschauer** [yakir12/TrackRoots.jl#6]

**Comment by yakir12** [comment]
Do you mean that it should avoid unnecessarily cloning `Kalman.jl` if it's already there? Meh, if it's there the clone action doesn't do anything. I think. Or did I misunderstand you?

**Comment by mschauer** [comment]
The build script actually errors in that case, so it is unclear if it finished the other tasks it has to do.

**Comment by yakir12** [comment]
Oh! Ok.

**Comment by yakir12** [comment]
I have "Kalman" and "" installed on my machine, and `Pkg.build("TrackRoots")` doesn't error out (now). But it would be great if you could check too. Thanks!
